## Importing Libraries

In [8]:
import pandas as pd
import numpy as np

## Reading Files

In [9]:
cv_train=pd.read_csv(r"F:\Edvancer course\ML with Python\Projects\Project 2\carvan_train.csv")
cv_test=pd.read_csv(r"F:\Edvancer course\ML with Python\Projects\Project 2\carvan_test.csv")

In [10]:
cv_train.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V77,V78,V79,V80,V81,V82,V83,V84,V85,V86
0,33,1,3,2,8,0,5,1,3,7,...,0,0,0,1,0,0,0,0,0,0
1,37,1,2,2,8,1,4,1,4,6,...,0,0,0,1,0,0,0,0,0,0
2,37,1,2,2,8,0,4,2,4,3,...,0,0,0,1,0,0,0,0,0,0
3,9,1,3,3,3,2,3,2,4,5,...,0,0,0,1,0,0,0,0,0,0
4,40,1,4,2,10,1,4,1,4,7,...,0,0,0,1,0,0,0,0,0,0

In [11]:
cv_train.shape

(5822, 86)

In [12]:
cv_test.shape

(4000, 85)

In [13]:
cv_test['V86']=np.nan

## Checking Null values

In [14]:
cv_train.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
      ..
V82    0
V83    0
V84    0
V85    0
V86    0
Length: 86, dtype: int64

In [15]:
cv_test.isnull().sum()

V1        0
V2        0
V3        0
V4        0
V5        0
       ...
V82       0
V83       0
V84       0
V85       0
V86    4000
Length: 86, dtype: int64

In [16]:
cv_train['V86'].value_counts()

0    5474
1     348
Name: V86, dtype: int64

In [17]:
cv_train['V1'].value_counts()

33    810
8     339
38    339
39    328
9     278
23    251
3     249
36    225
35    214
41    205
31    205
34    182
24    180
13    179
10    165
11    153
32    141
37    132
1     124
6     119
30    118
12    111
22     98
29     86
2      82
25     82
40     71
4      52
27     50
26     48
5      45
7      44
28     25
20     25
18     19
16     16
21     15
17      9
15      5
19      3
Name: V1, dtype: int64

## Creating Dummies

In [18]:
V1_dummies=pd.get_dummies(cv_train["V1"],prefix="CS")

In [19]:
cv_train.shape

(5822, 86)

In [20]:
cv_test.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V77,V78,V79,V80,V81,V82,V83,V84,V85,V86
0,33,1,4,2,8,0,6,0,3,5,...,0,0,0,1,0,0,0,0,0,NaN
1,6,1,3,2,2,0,5,0,4,5,...,0,0,0,1,0,0,0,0,0,NaN
2,39,1,3,3,9,1,4,2,3,5,...,0,0,0,1,0,0,0,0,0,NaN
3,9,1,2,3,3,2,3,2,4,5,...,0,0,0,1,0,0,0,0,0,NaN
4,31,1,2,4,7,0,2,0,7,9,...,0,0,0,1,0,0,0,0,0,NaN

In [21]:
V1_dummies.head()

,CS_1,CS_2,CS_3,CS_4,CS_5,CS_6,CS_7,CS_8,CS_9,CS_10,...,CS_32,CS_33,CS_34,CS_35,CS_36,CS_37,CS_38,CS_39,CS_40,CS_41
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

## Concatenating files

In [22]:
cv_train=pd.concat([cv_train,V1_dummies],1)
cv_train=cv_train.drop(["V1"],1)

In [23]:
cv_train=cv_train.drop(["V5"],1)

In [24]:
cv_test.isnull().sum()

V1        0
V2        0
V3        0
V4        0
V5        0
       ...
V82       0
V83       0
V84       0
V85       0
V86    4000
Length: 86, dtype: int64

## Droping the target variable from test data

In [28]:
x_train=cv_train.drop('V86',axis=1)
y_train=cv_train['V86']
x_test=cv_train.drop('V86',axis=1)
y_test=cv_train['V86']

In [29]:
 y_train.dtype

dtype('int64')

## Building the  Decision tree model

In [30]:
from sklearn import tree

In [31]:
# creating a decision tree class object
dtree=tree.DecisionTreeClassifier(criterion="entropy",max_leaf_nodes=10,
                                  class_weight="balanced")

In [32]:
dtree.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight='balanced',
                       criterion='entropy', max_depth=None, max_features=None,
                       max_leaf_nodes=10, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       presort='deprecated', random_state=None,
                       splitter='best')

In [33]:
tree.export_graphviz(dtree,out_file="mytree.dot",
                     feature_names=x_train.columns,
                    class_names=["0","1"],
                     proportion=True)

In [34]:
predicted=dtree.predict(x_test)

In [35]:
df_test=pd.DataFrame(list(zip(y_test,predicted)),columns=["real","predicted"])

In [36]:
k=pd.crosstab(df_test['real'],df_test["predicted"])

In [37]:
k

predicted     0     1
real
0          3917  1557
1           106   242

In [38]:
TP=k.iloc[1,1]
TN=k.iloc[0,0]
FP=k.iloc[0,1]
FN=k.iloc[1,0]
P=TP+FN
N=TN+FP


print('Accuracy is :',(TP+TN)/(P+N))
print('Sensitivity is :',TP/P)
print('Specificity is :',TN/N)

Accuracy is : 0.7143593266918584
Sensitivity is : 0.6954022988505747
Specificity is : 0.7155644866642309

In [39]:
list(range(2,20))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [40]:
max_nodes=[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
max_nodes

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [41]:
beta=2
max_FB=0
mx_dp=list(range(2,20))
crtr=['gini','entropy']
mn_samp_spl=list(range(2,20))

for i in mx_dp:
    for j in crtr:
        for kk in mn_samp_spl:
            mytree = tree.DecisionTreeClassifier(criterion=j,max_depth=i,min_samples_split=kk,
                                             class_weight="balanced")
            dtree.fit(x_train,y_train)
            predicted=dtree.predict(x_test)

            df_test=pd.DataFrame(list(zip(y_test,predicted)),columns=["real","predicted"])

            k=pd.crosstab(df_test['real'],df_test["predicted"])
            TP=k.iloc[1,1]
            TN=k.iloc[0,0]
            FP=k.iloc[0,1]
            FN=k.iloc[1,0]
            P=TP+FN
            N=TN+FP
            Precision=TP/(TP+FP)
            Recall=TP/P
            FB=(1+beta**2)*Precision*Recall/((beta**2)*Precision+Recall)
            if FB>max_FB:
                max_FB=FB
                optimal_crt=j
                optimal_depth=i
                optimal_min_samp_split=kk

print('criteria ',optimal_crt)
print('depth ',optimal_depth)
print('min sample split ',optimal_min_samp_split)

criteria  gini
depth  2
min sample split  2

In [42]:
for i in mx_dp:
    for j in crtr:
        for kk in mn_samp_spl:
            print(i , ':',j,':',kk )

2 : gini : 2
2 : gini : 3
2 : gini : 4
2 : gini : 5
2 : gini : 6
2 : gini : 7
2 : gini : 8
2 : gini : 9
2 : gini : 10
2 : gini : 11
2 : gini : 12
2 : gini : 13
2 : gini : 14
2 : gini : 15
2 : gini : 16
2 : gini : 17
2 : gini : 18
2 : gini : 19
2 : entropy : 2
2 : entropy : 3
2 : entropy : 4
2 : entropy : 5
2 : entropy : 6
2 : entropy : 7
2 : entropy : 8
2 : entropy : 9
2 : entropy : 10
2 : entropy : 11
2 : entropy : 12
2 : entropy : 13
2 : entropy : 14
2 : entropy : 15
2 : entropy : 16
2 : entropy : 17
2 : entropy : 18
2 : entropy : 19
3 : gini : 2
3 : gini : 3
3 : gini : 4
3 : gini : 5
3 : gini : 6
3 : gini : 7
3 : gini : 8
3 : gini : 9
3 : gini : 10
3 : gini : 11
3 : gini : 12
3 : gini : 13
3 : gini : 14
3 : gini : 15
3 : gini : 16
3 : gini : 17
3 : gini : 18
3 : gini : 19
3 : entropy : 2
3 : entropy : 3
3 : entropy : 4
3 : entropy : 5
3 : entropy : 6
3 : entropy : 7
3 : entropy : 8
3 : entropy : 9
3 : entropy : 10
3 : entropy : 11
3 : entropy : 12
3 : entropy : 13
3 : entropy : 14
3 : entropy : 15
3 : entropy : 16
3 : entropy : 17
3 : entropy : 18
3 : entropy : 19
4 : gini : 2
4 : gini : 3
4 : gini : 4
4 : gini : 5
4 : gini : 6
4 : gini : 7
4 : gini : 8
4 : gini : 9
4 : gini : 10
4 : gini : 11
4 : gini : 12
4 : gini : 13
4 : gini : 14
4 : gini : 15
4 : gini : 16
4 : gini : 17
4 : gini : 18
4 : gini : 19
4 : entropy : 2
4 : entropy : 3
4 : entropy : 4
4 : entropy : 5
4 : entropy : 6
4 : entropy : 7
4 : entropy : 8
4 : entropy : 9
4 : entropy : 10
4 : entropy : 11
4 : entropy : 12
4 : entropy : 13
4 : entropy : 14
4 : entropy : 15
4 : entropy : 16
4 : entropy : 17
4 : entropy : 18
4 : entropy : 19
5 : gini : 2
5 : gini : 3
5 : gini : 4
5 : gini : 5
5 : gini : 6
5 : gini : 7
5 : gini : 8
5 : gini : 9
5 : gini : 10
5 : gini : 11
5 : gini : 12
5 : gini : 13
5 : gini : 14
5 : gini : 15
5 : gini : 16
5 : gini : 17
5 : gini : 18
5 : gini : 19
5 : entropy : 2
5 : entropy : 3
5 : entropy : 4
5 : entropy : 5
5 : entropy : 6
5 : entropy : 7
5 : entropy : 8
5 : entropy : 9
5 : entropy : 10
5 : entropy : 11
5 : entropy : 12
5 : entropy : 13
5 : entropy : 14
5 : entropy : 15
5 : entropy : 16
5 : entropy : 17
5 : entropy : 18
5 : entropy : 19
6 : gini : 2
6 : gini : 3
6 : gini : 4
6 : gini : 5
6 : gini : 6
6 : gini : 7
6 : gini : 8
6 : gini : 9
6 : gini : 10
6 : gini : 11
6 : gini : 12
6 : gini : 13
6 : gini : 14
6 : gini : 15
6 : gini : 16
6 : gini : 17
6 : gini : 18
6 : gini : 19
6 : entropy : 2
6 : entropy : 3
6 : entropy : 4
6 : entropy : 5
6 : entropy : 6
6 : entropy : 7
6 : entropy : 8
6 : entropy : 9
6 : entropy : 10
6 : entropy : 11
6 : entropy : 12
6 : entropy : 13
6 : entropy : 14
6 : entropy : 15
6 : entropy : 16
6 : entropy : 17
6 : entropy : 18
6 : entropy : 19
7 : gini : 2
7 : gini : 3
7 : gini : 4
7 : gini : 5
7 : gini : 6
7 : gini : 7
7 : gini : 8
7 : gini : 9
7 : gini : 10
7 : gini : 11
7 : gini : 12
7 : gini : 13
7 : gini : 14
7 : gini : 15
7 : gini : 16
7 : gini : 17
7 : gini : 18
7 : gini : 19
7 : entropy : 2
7 : entropy : 3
7 : entropy : 4
7 : entropy : 5
7 : entropy : 6
7 : entropy : 7
7 : entropy : 8
7 : entropy : 9
7 : entropy : 10
7 : entropy : 11
7 : entropy : 12
7 : entropy : 13
7 : entropy : 14
7 : entropy : 15
7 : entropy : 16
7 : entropy : 17
7 : entropy : 18
7 : entropy : 19
8 : gini : 2
8 : gini : 3
8 : gini : 4
8 : gini : 5
8 : gini : 6
8 : gini : 7
8 : gini : 8
8 : gini : 9
8 : gini : 10
8 : gini : 11
8 : gini : 12
8 : gini : 13
8 : gini : 14
8 : gini : 15
8 : gini : 16
8 : gini : 17
8 : gini : 18
8 : gini : 19
8 : entropy : 2
8 : entropy : 3
8 : entropy : 4
8 : entropy : 5
8 : entropy : 6
8 : entropy : 7
8 : entropy : 8
8 : entropy : 9
8 : entropy : 10
8 : entropy : 11
8 : entropy : 12
8 : entropy : 13
8 : entropy : 14
8 : entropy : 15
8 : entropy : 16
8 : entropy : 17
8 : entropy : 18
8 : entropy : 19
9 : gini : 2
9 : gini : 3
9 : gini : 4
9 : gini : 5
9 : gini : 6
9 : gini : 7
9 : gini : 8
9 : gini : 9
9 : gini : 10
9 : gini : 11
9 : gini : 12
9 : gini : 13
9 : gini : 14
9 : gini : 15
9 : gini : 16
9 : gini : 17
9 : gini : 18
9 : gini : 19
9 : entropy : 2
9 : entropy : 3
9 : entropy : 4
9 : entropy : 5
9 : entropy : 6
9 : entropy : 7
9 : entropy : 8
9 : entropy : 9
9 : entropy : 10
9 : entropy : 11
9 : entropy : 12
9 : entropy : 13
9 : entropy : 14
9 : entropy : 15
9 : entropy : 16
9 : entropy : 17
9 : entropy : 18
9 : entropy : 19
10 : gini : 2
10 : gini : 3
10 : gini : 4
10 : gini : 5
10 : gini : 6
10 : gini : 7
10 : gini : 8
10 : gini : 9
10 : gini : 10
10 : gini : 11
10 : gini : 12
10 : gini : 13
10 : gini : 14
10 : gini : 15
10 : gini : 16
10 : gini : 17
10 : gini : 18
10 : gini : 19
10 : entropy : 2
10 : entropy : 3
10 : entropy : 4
10 : entropy : 5
10 : entropy : 6
10 : entropy : 7
10 : entropy : 8
10 : entropy : 9
10 : entropy : 10
10 : entropy : 11
10 : entropy : 12
10 : entropy : 13
10 : entropy : 14
10 : entropy : 15
10 : entropy : 16
10 : entropy : 17
10 : entropy : 18
10 : entropy : 19
11 : gini : 2
11 : gini : 3
11 : gini : 4
11 : gini : 5
11 : gini : 6
11 : gini : 7
11 : gini : 8
11 : gini : 9
11 : gini : 10
11 : gini : 11
11 : gini : 12
11 : gini : 13
11 : gini : 14
11 : gini : 15
11 : gini : 16
11 : gini : 17
11 : gini : 18
11 : gini : 19
11 : entropy : 2
11 : entropy : 3
11 : entropy : 4
11 : entropy : 5
11 : entropy : 6
11 : entropy : 7
11 : entropy : 8
11 : entropy : 9
11 : entropy : 10
11 : entropy : 11
11 : entropy : 12
11 : entropy : 13
11 : entropy : 14
11 : entropy : 15
11 : entropy : 16
11 : entropy : 17
11 : entropy : 18
11 : entropy : 19
12 : gini : 2
12 : gini : 3
12 : gini : 4
12 : gini : 5
12 : gini : 6
12 : gini : 7
12 : gini : 8
12 : gini : 9
12 : gini : 10
12 : gini : 11
12 : gini : 12
12 : gini : 13
12 : gini : 14
12 : gini : 15
12 : gini : 16
12 : gini : 17
12 : gini : 18
12 : gini : 19
12 : entropy : 2
12 : entropy : 3
12 : entropy : 4
12 : entropy : 5
12 : entropy : 6
12 : entropy : 7
12 : entropy : 8
12 : entropy : 9
12 : entropy : 10
12 : entropy : 11
12 : entropy : 12
12 : entropy : 13
12 : entropy : 14
12 : entropy : 15
12 : entropy : 16
12 : entropy : 17
12 : entropy : 18
12 : entropy : 19
13 : gini : 2
13 : gini : 3
13 : gini : 4
13 : gini : 5
13 : gini : 6
13 : gini : 7
13 : gini : 8
13 : gini : 9
13 : gini : 10
13 : gini : 11
13 : gini : 12
13 : gini : 13
13 : gini : 14
13 : gini : 15
13 : gini : 16
13 : gini : 17
13 : gini : 18
13 : gini : 19
13 : entropy : 2
13 : entropy : 3
13 : entropy : 4
13 : entropy : 5
13 : entropy : 6
13 : entropy : 7
13 : entropy : 8
13 : entropy : 9
13 : entropy : 10
13 : entropy : 11
13 : entropy : 12
13 : entropy : 13
13 : entropy : 14
13 : entropy : 15
13 : entropy : 16
13 : entropy : 17
13 : entropy : 18
13 : entropy : 19
14 : gini : 2
14 : gini : 3
14 : gini : 4
14 : gini : 5
14 : gini : 6
14 : gini : 7
14 : gini : 8
14 : gini : 9
14 : gini : 10
14 : gini : 11
14 : gini : 12
14 : gini : 13
14 : gini : 14
14 : gini : 15
14 : gini : 16
14 : gini : 17
14 : gini : 18
14 : gini : 19
14 : entropy : 2
14 : entropy : 3
14 : entropy : 4
14 : entropy : 5
14 : entropy : 6
14 : entropy : 7
14 : entropy : 8
14 : entropy : 9
14 : entropy : 10
14 : entropy : 11
14 : entropy : 12
14 : entropy : 13
14 : entropy : 14
14 : entropy : 15
14 : entropy : 16
14 : entropy : 17
14 : entropy : 18
14 : entropy : 19
15 : gini : 2
15 : gini : 3
15 : gini : 4
15 : gini : 5
15 : gini : 6
15 : gini : 7
15 : gini : 8
15 : gini : 9
15 : gini : 10
15 : gini : 11
15 : gini : 12
15 : gini : 13
15 : gini : 14
15 : gini : 15
15 : gini : 16
15 : gini : 17
15 : gini : 18
15 : gini : 19
15 : entropy : 2
15 : entropy : 3
15 : entropy : 4
15 : entropy : 5
15 : entropy : 6
15 : entropy : 7
15 : entropy : 8
15 : entropy : 9
15 : entropy : 10
15 : entropy : 11
15 : entropy : 12
15 : entropy : 13
15 : entropy : 14
15 : entropy : 15
15 : entropy : 16
15 : entropy : 17
15 : entropy : 18
15 : entropy : 19
16 : gini : 2
16 : gini : 3
16 : gini : 4
16 : gini : 5
16 : gini : 6
16 : gini : 7
16 : gini : 8
16 : gini : 9
16 : gini : 10
16 : gini : 11
16 : gini : 12
16 : gini : 13
16 : gini : 14
16 : gini : 15
16 : gini : 16
16 : gini : 17
16 : gini : 18
16 : gini : 19
16 : entropy : 2
16 : entropy : 3
16 : entropy : 4
16 : entropy : 5
16 : entropy : 6
16 : entropy : 7
16 : entropy : 8
16 : entropy : 9
16 : entropy : 10
16 : entropy : 11
16 : entropy : 12
16 : entropy : 13
16 : entropy : 14
16 : entropy : 15
16 : entropy : 16
16 : entropy : 17
16 : entropy : 18
16 : entropy : 19
17 : gini : 2
17 : gini : 3
17 : gini : 4
17 : gini : 5
17 : gini : 6
17 : gini : 7
17 : gini : 8
17 : gini : 9
17 : gini : 10
17 : gini : 11
17 : gini : 12
17 : gini : 13
17 : gini : 14
17 : gini : 15
17 : gini : 16
17 : gini : 17
17 : gini : 18
17 : gini : 19
17 : entropy : 2
17 : entropy : 3
17 : entropy : 4
17 : entropy : 5
17 : entropy : 6
17 : entropy : 7
17 : entropy : 8
17 : entropy : 9
17 : entropy : 10
17 : entropy : 11
17 : entropy : 12
17 : entropy : 13
17 : entropy : 14
17 : entropy : 15
17 : entropy : 16
17 : entropy : 17
17 : entropy : 18
17 : entropy : 19
18 : gini : 2
18 : gini : 3
18 : gini : 4
18 : gini : 5
18 : gini : 6
18 : gini : 7
18 : gini : 8
18 : gini : 9
18 : gini : 10
18 : gini : 11
18 : gini : 12
18 : gini : 13
18 : gini : 14
18 : gini : 15
18 : gini : 16
18 : gini : 17
18 : gini : 18
18 : gini : 19
18 : entropy : 2
18 : entropy : 3
18 : entropy : 4
18 : entropy : 5
18 : entropy : 6
18 : entropy : 7
18 : entropy : 8
18 : entropy : 9
18 : entropy : 10
18 : entropy : 11
18 : entropy : 12
18 : entropy : 13
18 : entropy : 14
18 : entropy : 15
18 : entropy : 16
18 : entropy : 17
18 : entropy : 18
18 : entropy : 19
19 : gini : 2
19 : gini : 3
19 : gini : 4
19 : gini : 5
19 : gini : 6
19 : gini : 7
19 : gini : 8
19 : gini : 9
19 : gini : 10
19 : gini : 11
19 : gini : 12
19 : gini : 13
19 : gini : 14
19 : gini : 15
19 : gini : 16
19 : gini : 17
19 : gini : 18
19 : gini : 19
19 : entropy : 2
19 : entropy : 3
19 : entropy : 4
19 : entropy : 5

19 : entropy : 6
19 : entropy : 7
19 : entropy : 8
19 : entropy : 9
19 : entropy : 10
19 : entropy : 11
19 : entropy : 12
19 : entropy : 13
19 : entropy : 14
19 : entropy : 15
19 : entropy : 16
19 : entropy : 17
19 : entropy : 18
19 : entropy : 19

In [43]:
max_nodes

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [44]:
dtree=tree.DecisionTreeClassifier(criterion="gini",
                                  max_leaf_nodes=17,class_weight="balanced")
dtree.fit(x_train,y_train)
predicted=dtree.predict(x_test)

In [45]:
predicted

array([1, 0, 0, ..., 1, 1, 1], dtype=int64)

In [46]:
pd.DataFrame(predicted).to_csv("carvan-rf_github.csv",index=False)